"""empty message

Revision ID: e03d17a0b25c
Revises: None
Create Date: 2016-10-31 16:25:07.554567

"""

# revision identifiers, used by Alembic.
revision = 'e03d17a0b25c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('image_url', sa.Unicode(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part', 'image_url')
    ### end Alembic commands ###
