"""empty message

Revision ID: e46e0671667c
Revises: e03d17a0b25c
Create Date: 2016-10-31 18:15:26.290817

"""

# revision identifiers, used by Alembic.
revision = 'e46e0671667c'
down_revision = 'e03d17a0b25c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    ### end Alembic commands ###
