"""empty message

Revision ID: f516cfc88b54
Revises: e46e0671667c
Create Date: 2016-10-31 18:16:03.598084

"""

# revision identifiers, used by Alembic.
revision = 'f516cfc88b54'
down_revision = 'e46e0671667c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part', 'price')
    ### end Alembic commands ###
